// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// bfa_gd_gibbs
List bfa_gd_gibbs(NumericMatrix Linit, NumericMatrix Finit, NumericVector xi_init, double phi_init, NumericVector zeta_init, NumericVector theta_init, double kappa_init, NumericMatrix Y22init, NumericMatrix Y21, NumericMatrix Y31, NumericMatrix Y32, int nsamp, int burnin, int thin, double rho_0, double alpha_0, double delta_0, double lambda_0, double nu_0, double beta_0, double eta_0, double tau_0, bool hetero_factors, bool display_progress);
RcppExport SEXP vicar_bfa_gd_gibbs(SEXP LinitSEXP, SEXP FinitSEXP, SEXP xi_initSEXP, SEXP phi_initSEXP, SEXP zeta_initSEXP, SEXP theta_initSEXP, SEXP kappa_initSEXP, SEXP Y22initSEXP, SEXP Y21SEXP, SEXP Y31SEXP, SEXP Y32SEXP, SEXP nsampSEXP, SEXP burninSEXP, SEXP thinSEXP, SEXP rho_0SEXP, SEXP alpha_0SEXP, SEXP delta_0SEXP, SEXP lambda_0SEXP, SEXP nu_0SEXP, SEXP beta_0SEXP, SEXP eta_0SEXP, SEXP tau_0SEXP, SEXP hetero_factorsSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Linit(LinitSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Finit(FinitSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xi_init(xi_initSEXP);
    Rcpp::traits::input_parameter< double >::type phi_init(phi_initSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type zeta_init(zeta_initSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta_init(theta_initSEXP);
    Rcpp::traits::input_parameter< double >::type kappa_init(kappa_initSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y22init(Y22initSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y21(Y21SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y31(Y31SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y32(Y32SEXP);
    Rcpp::traits::input_parameter< int >::type nsamp(nsampSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< double >::type rho_0(rho_0SEXP);
    Rcpp::traits::input_parameter< double >::type alpha_0(alpha_0SEXP);
    Rcpp::traits::input_parameter< double >::type delta_0(delta_0SEXP);
    Rcpp::traits::input_parameter< double >::type lambda_0(lambda_0SEXP);
    Rcpp::traits::input_parameter< double >::type nu_0(nu_0SEXP);
    Rcpp::traits::input_parameter< double >::type beta_0(beta_0SEXP);
    Rcpp::traits::input_parameter< double >::type eta_0(eta_0SEXP);
    Rcpp::traits::input_parameter< double >::type tau_0(tau_0SEXP);
    Rcpp::traits::input_parameter< bool >::type hetero_factors(hetero_factorsSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(bfa_gd_gibbs(Linit, Finit, xi_init, phi_init, zeta_init, theta_init, kappa_init, Y22init, Y21, Y31, Y32, nsamp, burnin, thin, rho_0, alpha_0, delta_0, lambda_0, nu_0, beta_0, eta_0, tau_0, hetero_factors, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// bfa_gs_linked_gibbs
List bfa_gs_linked_gibbs(NumericMatrix Linit, NumericMatrix Finit, NumericVector xi_init, double phi_init, NumericVector zeta_init, NumericMatrix Y22init, NumericMatrix Y21, NumericMatrix Y31, NumericMatrix Y32, int nsamp, int burnin, int thin, double rho_0, double alpha_0, double beta_0, double eta_0, double tau_0, bool display_progress);
RcppExport SEXP vicar_bfa_gs_linked_gibbs(SEXP LinitSEXP, SEXP FinitSEXP, SEXP xi_initSEXP, SEXP phi_initSEXP, SEXP zeta_initSEXP, SEXP Y22initSEXP, SEXP Y21SEXP, SEXP Y31SEXP, SEXP Y32SEXP, SEXP nsampSEXP, SEXP burninSEXP, SEXP thinSEXP, SEXP rho_0SEXP, SEXP alpha_0SEXP, SEXP beta_0SEXP, SEXP eta_0SEXP, SEXP tau_0SEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Linit(LinitSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Finit(FinitSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xi_init(xi_initSEXP);
    Rcpp::traits::input_parameter< double >::type phi_init(phi_initSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type zeta_init(zeta_initSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y22init(Y22initSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y21(Y21SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y31(Y31SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y32(Y32SEXP);
    Rcpp::traits::input_parameter< int >::type nsamp(nsampSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< double >::type rho_0(rho_0SEXP);
    Rcpp::traits::input_parameter< double >::type alpha_0(alpha_0SEXP);
    Rcpp::traits::input_parameter< double >::type beta_0(beta_0SEXP);
    Rcpp::traits::input_parameter< double >::type eta_0(eta_0SEXP);
    Rcpp::traits::input_parameter< double >::type tau_0(tau_0SEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(bfa_gs_linked_gibbs(Linit, Finit, xi_init, phi_init, zeta_init, Y22init, Y21, Y31, Y32, nsamp, burnin, thin, rho_0, alpha_0, beta_0, eta_0, tau_0, display_progress));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"vicar_bfa_gd_gibbs", (DL_FUNC) &vicar_bfa_gd_gibbs, 24},
    {"vicar_bfa_gs_linked_gibbs", (DL_FUNC) &vicar_bfa_gs_linked_gibbs, 18},
    {NULL, NULL, 0}
};

RcppExport void R_init_vicar(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
