# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

update_fC <- function(LY, xi_current, theta_current) {
    .Call('vicar_update_fC', PACKAGE = 'vicar', LY, xi_current, theta_current)
}

